# =============================================================================
# Proof of Aid — Team 05 — 0001: claims, evidence_files, participants, challenges
# Copyright (c) 2026 Guillermo Palau Fernández, Iago Rey Rey, Francisco Barbero Vázquez
# Licensed under the MIT License. See LICENSE for details.
# Built with dbv-specs-ops · https://github.com/davidbuenov/dbv-specs-ops
# =============================================================================
"""0001 initial tables

Revision ID: 199e2ea9e4ec
Revises: 
Create Date: 2026-09-24 15:45:56.421698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199e2ea9e4ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_challenges_address'), 'challenges', ['address'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id_hex', sa.String(length=66), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_region', sa.String(length=120), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('metadata_hash_hex', sa.String(length=66), nullable=False),
    sa.Column('created_by', sa.String(length=42), nullable=False),
    sa.Column('auditor_address', sa.String(length=42), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_id_hex'), 'claims', ['claim_id_hex'], unique=True)
    op.create_index(op.f('ix_claims_created_by'), 'claims', ['created_by'], unique=False)
    op.create_table('participants',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('organization', sa.String(length=42), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('organization', 'internal_verifier', 'auditor')", name='ck_participant_role'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('evidence_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('sha256_hex', sa.String(length=66), nullable=False),
    sa.Column('storage_name', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=42), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'sha256_hex', name='uq_file_per_claim')
    )
    op.create_index(op.f('ix_evidence_files_claim_id'), 'evidence_files', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_files_claim_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_table('participants')
    op.drop_index(op.f('ix_claims_created_by'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id_hex'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_challenges_address'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
